import type { Question, QuestionType } from "./types"

// Mock question data for development
export const mockQuestions: Question[] = [
  {
    id: "1",
    stem: "What is the capital of France?",
    type: "SINGLE_CORRECT" as QuestionType,
    options: [
      { id: "1", text: "London", isCorrect: false },
      { id: "2", text: "Berlin", isCorrect: false },
      { id: "3", text: "Paris", isCorrect: true },
      { id: "4", text: "Madrid", isCorrect: false },
    ],
    correctCount: 1,
    tags: ["geography", "europe", "capitals"],
    topic: "Geography",
    subtopic: "European Capitals",
    difficulty: 2,
    explanation: "Paris is the capital and largest city of France.",
    version: 1,
    history: [],
    createdBy: "instructor@mcq.com",
    updatedBy: "instructor@mcq.com",
    isPublished: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    stem: "Which of the following are prime numbers? (Select all that apply)",
    type: "MULTI_SELECT" as QuestionType,
    options: [
      { id: "1", text: "2", isCorrect: true },
      { id: "2", text: "4", isCorrect: false },
      { id: "3", text: "7", isCorrect: true },
      { id: "4", text: "9", isCorrect: false },
      { id: "5", text: "11", isCorrect: true },
    ],
    correctCount: 3,
    tags: ["mathematics", "number-theory", "primes"],
    topic: "Mathematics",
    subtopic: "Number Theory",
    difficulty: 3,
    explanation:
      "Prime numbers are natural numbers greater than 1 that have no positive divisors other than 1 and themselves.",
    version: 1,
    history: [],
    createdBy: "instructor@mcq.com",
    updatedBy: "instructor@mcq.com",
    isPublished: true,
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "3",
    stem: "The Earth is flat.",
    type: "TRUE_FALSE" as QuestionType,
    options: [
      { id: "1", text: "True", isCorrect: false },
      { id: "2", text: "False", isCorrect: true },
    ],
    correctCount: 1,
    tags: ["science", "earth", "basic-facts"],
    topic: "Science",
    subtopic: "Earth Science",
    difficulty: 1,
    explanation: "The Earth is approximately spherical in shape, not flat.",
    version: 1,
    history: [],
    createdBy: "instructor@mcq.com",
    updatedBy: "instructor@mcq.com",
    isPublished: true,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
]
